= Scratch

== Misc

> THE SEA SPAWN OF PURPLE ROCKS

> Visitors to a string of islands called the Purple Rocks (in the Forgotten Realms setting) might notice one curious fact about the islands’ human inhabitants: no infants or elderly are among them. This is because babies born to the Rocklanders are cast into the sea and claimed by a kraken named Slarkrethel. The experience transforms the children into fanatics dedicated to the kraken. They return from the sea as humans, but when they reach old age, they transform into sea spawn and rejoin their master in the dark depths. Some children return having suffered partial transformations, leaving them semi-bestial until their full transformation when they reach old age. These wretches are hidden until their final change, to keep the secret of the Purple Rocks.

> Kraken priests (described in appendix B) are the tenders of the kraken’s flock. Most of the priests are island natives, but some are merfolk, merrow, or sea elves that live in the water around the Purple Rocks.

== Pearce

Castle Whiteriver (Blower)
Castle Youngbloom (Davies)
Castle Longwatch (Goff)
Castle Horserunner (Pembroke)
Castle Alpenvalor (Pritchard)
PC's castle (Sharnwick)
