= Background

Like most gnomes, Zilzu delights in invention, exploration, and investigation; he loves jokes of all kinds, particularly puns and pranks; he is curious and impulsive.

Gnomes in the Quillsharpener line bear the Mark of Scribing, which makes them excellent scribes, notaries, interpreters, etc. The family facilitates communication across the land with speaking stones and other messaging magics; their famous neutrality has established them as a trustworthy third party in any dispute.

> A gnome who bears the Mark of Scribing can feel words as though they are living creatures, struggling to make their meaning known.
-- https://www.dndbeyond.com/races/gnome#MarkofScribingGnome

As an artificer, Zilzu works to commodify magic. Rather than cast spells, he uses his tools to create magical devices, such as the speaking stones used in the Quillsharpener family business.

His skill with magical items and information led Zilzu to become a city watch investigator. There, he honed his skills as an alchemist and detective. He blames himself for not being able to stop a wave of organized crime that ended up killing several other members of the watch.

Zilzu adventures because thinks he can make up for his failure by righting wrongs across the world.
